name: 03 - workflow runners


on: 
  workflow_dispatch:

jobs:
  macos-echo:
    runs-on: macos-latest
    steps:
        - name: Show OS
          run: |
            echo "this runner on ths macos latest"
            echo "runner os $RUNNER_OS"



  windows-echo:
    runs-on: windows-latest
    steps:
      - name: Show OS
        shell: bash
        run: | 
          echo "this job is running on an ubuntu runner."
          echo "Runner OS: $RUNNER_OS"
